import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { FaSquareWhatsapp } from "react-icons/fa6";
import WhatsAppButton from "@/components/WhatsAppButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RealState",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          {/* <FaSquareWhatsapp className="h-10 w-10 text-green-700 z-20 " /> */}
        <Navbar />
        {children}
        <WhatsAppButton/>
        <Footer />
      </body>
    </html>
  );
}
